In [1]:
from sklearn.datasets import load_iris
iris=load_iris()
X=iris.data
y=iris.target

In [2]:
print("features: ",iris.feature_names)
print("shape: ",X.shape)
print("data:\n",X)

features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
shape:  (150, 4)
data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.

In [3]:
print("target names: ",iris.target_names)
print("shape: ",y.shape)
print("target data:\n",y)

target names:  ['setosa' 'versicolor' 'virginica']
shape:  (150,)
target data:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [4]:
print("type of X: ",type(X))
print("type of y: ",type(y))

type of X:  <class 'numpy.ndarray'>
type of y:  <class 'numpy.ndarray'>


In [5]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)
knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [6]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [7]:
X_new=[[3,5,4,2],[5,4,3,2],[1,1,1,1]]
knn.predict(X_new)

array([2, 1, 0])

In [8]:
knn5=KNeighborsClassifier(n_neighbors=5)
knn5

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [9]:
knn5.fit(X,y)
knn5.predict(X_new)

array([1, 1, 0])

In [10]:
from sklearn.linear_model import LogisticRegression

logreg=LogisticRegression(solver='lbfgs',multi_class='auto')
logreg.fit(X,y)
y_pred=logreg.predict(X_new)
y_pred

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


array([0, 0, 0])


## - now lets split the dataframe into train and test dataset
## - fit the model to the training dataset
## - predict the output and match with the actual dataset to check the accuracy






In [11]:
from sklearn import metrics
from sklearn.model_selection import train_test_split


X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25, random_state=5)

In [12]:
knn5=KNeighborsClassifier(n_neighbors=5)
knn5.fit(X_train,y_train)
y_pred=knn5.predict(X_test)

print (metrics.accuracy_score(y_test,y_pred))

0.9473684210526315


In [13]:
knn1=KNeighborsClassifier(n_neighbors=1)
knn1.fit(X_train,y_train)
y_pred=knn5.predict(X_test)

print (metrics.accuracy_score(y_test,y_pred))

0.9473684210526315


In [14]:
logreg=LogisticRegression(solver='lbfgs',multi_class='auto')
logreg.fit(X_train,y_train)
y_pred=logreg.predict(X_test)

print (metrics.accuracy_score(y_test,y_pred))

0.9736842105263158
